version: "3.8"

networks:
  inception_dp:
    name: inception_dp
    driver: bridge

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception_dp

  wordpress:
    container_name: wordpress
    image: wordpress:42
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception_dp
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx:42
    build: ./requirements/nginx/
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception_dp
    depends_on:
      - wordpress
    ports:
      - "443:443"
